import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { spawn } from "node:child_process";
import { loadConfig, getAppDir, getBuildPath } from "../../src/config/loadConfig.js";
import { scanAppFiles } from "../../src/loader/fileScanner.js";
import { validateApp } from "../../src/validation/validateApp.js";
import { runPluginHook } from "../pluginHooks.js";
import { appLogger } from "../../src/utils/logger.js";

/**
 * Read runServer.ts (via its compiled runServer.js) and append bootstrap +
 * run logic into outputFolder/server.js.
 * The generated server.js loads runServer from the legonode package and runs it
 * with buildPath pointing to the output folder.
 */
function writeServerJs(buildPath: string): void {
  const serverJs = `#!/usr/bin/env node
/**
 * Generated by legonode build.
 * Runs the built app. Usage: node server.js
 * Options: --port/-p, --host/-H, --build-path; or PORT, HOST env vars.
 */
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// require.resolve("legonode") -> dist/src/index.js, so dirname x3 = package root
const legonodeMain = require.resolve("legonode");
const legonodeRoot = dirname(dirname(dirname(legonodeMain)));
const runServerPath = join(legonodeRoot, "dist/cli/runServer.js");
const { default: runServer } = await import(pathToFileURL(runServerPath).href);

function getArg(long, shorts) {
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length - 1; i++) {
    if (argv[i] === long || (shorts && shorts.includes(argv[i]))) return argv[i + 1];
  }
  return undefined;
}
const opts = {
  buildPath: getArg("--build-path") ?? __dirname,
  port: getArg("--port", ["-p"]) ?? (process.env.PORT ? Number(process.env.PORT) : undefined),
  host: getArg("--host", ["-H"]) ?? process.env.HOST ?? undefined,
};

runServer(opts).catch((err) => {
  console.error(err);
  process.exit(1);
});
`;
  const serverPath = join(buildPath, "server.js");
  writeFileSync(serverPath, serverJs, "utf-8");
  appLogger.info("  server.js written to " + serverPath);
}

const EVENT_EXTENSIONS = [".event.ts", ".event.js", ".event.mts", ".event.mjs"];

function countEventFiles(appDir: string): number {
  try {
    const eventsDir = join(resolve(appDir), "events");
    const entries = readdirSync(eventsDir, { withFileTypes: true });
    return entries.filter(
      (e) => e.isFile() && EVENT_EXTENSIONS.some((ext) => e.name.endsWith(ext))
    ).length;
  } catch {
    return 0;
  }
}

export type BuildOptions = {
  buildPath?: string;
};

export const buildCommand = {
  name: "build",
  run: async (opts: BuildOptions = {}) => {
    const cwd = process.cwd();
    const config = await loadConfig(cwd);
    const plugins = config.plugins;
    const appDir = getAppDir(config, cwd);
    if (!appDir) {
      appLogger.error("App directory not found");
      process.exit(1);
    }

    appLogger.info("legonode build");
    const valid = await validateApp(appDir, { isBuild: true });
    if (!valid) {
      process.exit(1);
    }

    const buildPath = opts.buildPath ? resolve(cwd, opts.buildPath) : getBuildPath(config, cwd);
    await runPluginHook(plugins, "onBuildStart", {
      command: "build",
      cwd,
      appDir,
      buildPath,
    });

    const routes = scanAppFiles(appDir);
    const events = countEventFiles(appDir);

    appLogger.info(`  ${routes.length} route(s), ${events} event(s)`);
    appLogger.info("  compiling...");

    const start = Date.now();
    const tsconfig = "tsconfig.json";

    return new Promise<void>((resolvePromise, reject) => {
      // Avoid using `shell: true` with args to prevent DEP0190 and reduce injection risk.
      // Prefer local `tsc` from `node_modules/.bin` for deterministic builds; fallback to `npx tsc`.
      const tscBin = resolve(cwd, "node_modules", ".bin", `tsc${process.platform === "win32" ? ".cmd" : ""}`);
      const useNpx = !existsSync(tscBin);
      const cmd = useNpx ? "npx" : tscBin;
      const args = useNpx
        ? ["tsc", "-p", tsconfig, "--outDir", buildPath]
        : ["-p", tsconfig, "--outDir", buildPath];

      const child = spawn(cmd, args, {
        stdio: "inherit",
        cwd,
      });
      child.on("exit", async (code) => {
        const elapsed = Date.now() - start;
        if (code === 0) {
          appLogger.info(`  done in ${elapsed}ms → ${buildPath}`);
          writeServerJs(buildPath);
          await runPluginHook(plugins, "onBuildComplete", {
            command: "build",
            cwd,
            appDir,
            buildPath,
          });
          resolvePromise();
        } else {
          const error = new Error(`tsc exited with code ${code}`);
          await runPluginHook(plugins, "onBuildError", {
            command: "build",
            cwd,
            appDir,
            buildPath,
            error,
          });
          reject(error);
        }
      });
      child.on("error", async (error) => {
        await runPluginHook(plugins, "onBuildError", {
          command: "build",
          cwd,
          appDir,
          buildPath,
          error,
        });
        reject(error);
      });
    });
  }
} as const;
